# Configuraciones del servidor
server:
  port: 8081
# Configuraciones de eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
# Configuraciones de spring cloud
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-bill
          uri: lb://ms-bill
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
            - TokenRelay=
  security:
    oauth2:
      client:
        provider:
          bills-app:
            issuer-uri: http://localhost:8080/realms/bills-realm
        registration:
          bills-app:
            provider: bills-app
            client-id: bills-client
            client-secret: HCmEEIj7RF6ddPIZPKN3Z7Ip1lnr2klB
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
